---
inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/HeredocIndentation:
  Enabled: false
